# Generated by Django 6.1.1 on 2026-10-02 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0002_payoutaccount_name_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_checks', to='payments.payoutaccount'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Name the bank returned.', max_length=160),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='id_full_name',
            field=models.CharField(blank=True, help_text='Name on the ID, from the ID registry.', max_length=160),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='name_match',
            field=models.BooleanField(help_text='Did the ID name match the bank account name?', null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Passed'), ('rejected', 'Failed')], default='pending', max_length=10),
        ),
    ]
