# Generated by Django 6.1.1 on 2026-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_kycsubmission_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='code_hash',
            field=models.CharField(max_length=100),
        ),
    ]
