# Generated by Django 6.1.1 on 2026-10-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_onetimepassword_code_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'KYC check'},
        ),
    ]
