# Generated by Django 6.1.1 on 2026-10-01 15:08

import apps.games.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('ticket_price', models.BigIntegerField(help_text='Minor units (kobo).')),
                ('pick_count', models.PositiveSmallIntegerField(help_text='How many numbers a player picks (N).')),
                ('number_max', models.PositiveSmallIntegerField(help_text='Numbers are drawn from 1..M.')),
                ('draw_time', models.TimeField(help_text='Daily draw time (Africa/Lagos). Ticket sales close at this time.')),
                ('max_lines_per_purchase', models.PositiveSmallIntegerField(default=10)),
                ('max_tickets_per_draw', models.PositiveIntegerField(default=100, help_text='Per player, per draw.')),
                ('is_active', models.BooleanField(default=True)),
                ('accent', models.CharField(default='violet', help_text='UI colour theme key.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['draw_time'],
            },
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open for sales'), ('locked', 'Sales closed'), ('drawn', 'Numbers drawn'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('opens_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closes_at', models.DateTimeField()),
                ('server_seed', models.CharField(default=apps.games.models.new_server_seed, editable=False, max_length=64)),
                ('server_seed_hash', models.CharField(editable=False, max_length=64)),
                ('client_seed', models.CharField(blank=True, editable=False, max_length=64)),
                ('winning_numbers', models.JSONField(blank=True, default=list)),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('total_stake', models.BigIntegerField(default=0)),
                ('total_prizes', models.BigIntegerField(default=0)),
                ('winner_count', models.PositiveIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('drawn_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draws', to='games.game')),
            ],
            options={
                'ordering': ['closes_at'],
            },
        ),
        migrations.CreateModel(
            name='PrizeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('match_count', models.PositiveSmallIntegerField()),
                ('payout_type', models.CharField(choices=[('fixed', 'Fixed multiple of stake'), ('pool', 'Share of draw pool (%), split between winners')], max_length=8)),
                ('value', models.DecimalField(decimal_places=2, help_text='Multiplier (e.g. 10) or pool % (e.g. 25)', max_digits=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_tiers', to='games.game')),
            ],
            options={
                'ordering': ['-match_count'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(default=apps.games.models.ticket_serial, max_length=20, unique=True)),
                ('numbers', models.JSONField()),
                ('is_quick_pick', models.BooleanField(default=False)),
                ('stake', models.BigIntegerField()),
                ('signature', models.CharField(max_length=64, unique=True)),
                ('purchased_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Awaiting draw'), ('won', 'Won'), ('lost', 'No win'), ('refunded', 'Refunded')], default='active', max_length=10)),
                ('match_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prize_amount', models.BigIntegerField(default=0)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='games.draw')),
                ('payout_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journaltransaction')),
                ('prize_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.prizetier')),
                ('purchase_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journaltransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='draw',
            index=models.Index(fields=['status', 'closes_at'], name='games_draw_status_e6f454_idx'),
        ),
        migrations.AddConstraint(
            model_name='draw',
            constraint=models.UniqueConstraint(fields=('game', 'draw_number'), name='unique_draw_number'),
        ),
        migrations.AddConstraint(
            model_name='prizetier',
            constraint=models.UniqueConstraint(fields=('game', 'match_count'), name='one_tier_per_match_count'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['draw', 'status'], name='games_ticke_draw_id_0eb2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', '-purchased_at'], name='games_ticke_user_id_666480_idx'),
        ),
    ]
