# Generated by Django 6.1.1 on 2026-10-02 08:58

import apps.games.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def existing_games_are_pick(apps, schema_editor):
    apps.get_model("games", "Game").objects.update(mode="pick")


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='carry_in',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draw',
            name='carry_out',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draw',
            name='consolation_winner_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draw',
            name='grand_winner_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draw',
            name='house_share',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draw',
            name='house_topup',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draw',
            name='prize_pool',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draw',
            name='spun_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='consolation_min_match',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='consolation_prize',
            field=models.BigIntegerField(default=700000, help_text='Minor units.'),
        ),
        migrations.AddField(
            model_name='game',
            name='grand_prize',
            field=models.BigIntegerField(default=10000000, help_text='Minor units. Paid for matching all numbers.'),
        ),
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('spin', 'Spin game (numbers given automatically, admin spins)'), ('pick', 'Pick-your-numbers daily draw')], default='spin', max_length=8),
        ),
        migrations.AddField(
            model_name='game',
            name='prize_pool_percent',
            field=models.PositiveSmallIntegerField(default=60, help_text='Share of sales paid out as prizes.'),
        ),
        migrations.AddField(
            model_name='game',
            name='schedule',
            field=models.JSONField(blank=True, default=apps.games.models.default_schedule, help_text='Spin games: daily play windows (Africa/Lagos), e.g. [["08:00","17:00"],["20:00","24:00"]].'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bonus_stake',
            field=models.BigIntegerField(default=0, help_text='Part of the stake paid from bonus credit.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prize_label',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('open', 'Open for sales'), ('locked', 'Closed — awaiting spin'), ('drawn', 'Numbers drawn'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='draw_time',
            field=models.TimeField(blank=True, help_text='Pick games: daily draw time (Africa/Lagos). Sales close at this time.', null=True),
        ),
        migrations.RunPython(existing_games_are_pick, migrations.RunPython.noop),
    ]
