# Generated by Django 6.1.1 on 2026-10-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_draw_carry_in_draw_carry_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='consolation_target',
            field=models.PositiveIntegerField(blank=True, help_text='Winner count chosen by the admin at spin time (blank = game setting).', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='consolation_winners',
            field=models.PositiveIntegerField(blank=True, help_text='Consolation winners per game. Blank = automatic (as many as the prize pool pays). If you set more than the pool can pay, the company pays the difference; fewer, and the unused money carries over to the next game.', null=True),
        ),
    ]
