# Generated by Django 6.1.1 on 2026-10-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_draw_consolation_target_game_consolation_winners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draw',
            name='consolation_target',
        ),
        migrations.RemoveField(
            model_name='game',
            name='consolation_min_match',
        ),
        migrations.RemoveField(
            model_name='game',
            name='consolation_winners',
        ),
        migrations.AlterField(
            model_name='game',
            name='prize_pool_percent',
            field=models.PositiveSmallIntegerField(default=60, help_text="Share of each batch's sales paid out as prizes. The rest is company profit."),
        ),
    ]
