# Generated by Django 6.1.1 on 2026-10-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_draw_consolation_target_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draw',
            options={'ordering': ['closes_at'], 'verbose_name': 'Game round'},
        ),
        migrations.AlterField(
            model_name='game',
            name='prize_pool_percent',
            field=models.PositiveSmallIntegerField(default=60, help_text="Share of each batch's sales paid out as prizes. The rest is company profit.", verbose_name='Prize share of sales (%)'),
        ),
    ]
