# Generated by Django 6.1.1 on 2026-10-02 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_bonus', models.DecimalField(decimal_places=2, help_text='Bonus credited to every new verified player (₦). Play-only. 0 = off.', max_digits=14)),
                ('min_deposit', models.DecimalField(decimal_places=2, help_text='Smallest deposit allowed (₦).', max_digits=14)),
                ('max_deposit', models.DecimalField(decimal_places=2, help_text='Largest single deposit (₦).', max_digits=14)),
                ('tier1_daily_deposit_limit', models.DecimalField(decimal_places=2, help_text='Daily deposit cap before ID verification (₦).', max_digits=14)),
                ('default_daily_deposit_limit', models.DecimalField(decimal_places=2, help_text='Daily deposit cap for verified players (₦).', max_digits=14)),
                ('tier1_max_stake_per_purchase', models.DecimalField(decimal_places=2, help_text='Most a Tier 1 (unverified ID) player can spend per play (₦).', max_digits=14)),
                ('min_withdrawal', models.DecimalField(decimal_places=2, help_text='Smallest withdrawal allowed (₦).', max_digits=14)),
                ('withdrawal_review_threshold', models.DecimalField(decimal_places=2, help_text='Withdrawals at or above this go to manual review (₦).', max_digits=14)),
                ('max_withdrawals_per_day', models.PositiveSmallIntegerField(help_text='More than this in 24h goes to review.')),
                ('new_account_review_hours', models.PositiveIntegerField(help_text='Withdrawals from accounts younger than this are reviewed.')),
                ('aml_wager_multiplier', models.DecimalField(decimal_places=2, help_text='Deposits must be played this many times before withdrawal (1 = once).', max_digits=4)),
                ('limit_increase_cooldown_hours', models.PositiveIntegerField(help_text="Delay before a player's raised limit applies.")),
                ('auto_spin_after_minutes', models.PositiveIntegerField(help_text='Spin closed games automatically after this many minutes if no admin has. 0 = admin only.')),
                ('kyc_require_bank_name_match', models.BooleanField(help_text='KYC passes only if the name on the ID matches the bank account name.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
