# Generated by Django 6.1.1 on 2026-10-03 08:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='coin_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Naira value of 1 coin. Players buy, play, win and cash out in coins at this rate.', max_digits=14),
        ),
    ]
