# Generated by Django 6.1.1 on 2026-10-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platformsettings_coin_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='coin_packages',
            field=models.CharField(default='100,300,500,1000,2000,5000', help_text='Coin packages on the Buy coins page, comma-separated (e.g. 100,300,500,1000).', max_length=120),
        ),
    ]
