# Generated by Django 6.1.1 on 2026-10-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platformsettings_coin_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='max_deposit',
            field=models.DecimalField(decimal_places=2, help_text='Largest single coin purchase, in naira.', max_digits=14, verbose_name='Maximum coin purchase (₦)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='min_deposit',
            field=models.DecimalField(decimal_places=2, help_text='Smallest coin purchase, in naira.', max_digits=14, verbose_name='Minimum coin purchase (₦)'),
        ),
    ]
