# Generated by Django 6.1.1 on 2026-10-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsiblegamingsettings',
            options={'verbose_name': 'Responsible gaming settings', 'verbose_name_plural': 'Responsible gaming settings'},
        ),
    ]
