# Generated by Django 6.1.1 on 2026-10-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutaccount',
            name='name_verified',
            field=models.BooleanField(default=False, help_text="Account name matches the player's verified ID."),
        ),
    ]
