# Generated by Django 6.1.1 on 2026-10-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payoutaccount_name_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='channel',
            field=models.CharField(choices=[('any', 'Any method (chosen at checkout)'), ('card', 'Debit card'), ('bank_transfer', 'Bank transfer'), ('ussd', 'USSD'), ('mobile_money', 'Mobile money (OPay, PalmPay…)')], max_length=20),
        ),
    ]
