# Generated by Django 6.1.1 on 2026-10-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_deposit_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Coin purchase'},
        ),
    ]
