# Generated by Django 6.1.1 on 2026-10-01 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('tx_type', models.CharField(choices=[('deposit', 'Deposit'), ('ticket_purchase', 'Ticket purchase'), ('prize_payout', 'Prize payout'), ('pool_topup', 'House top-up of prize pool'), ('pool_settlement', 'Pool settlement to house'), ('ticket_refund', 'Ticket refund'), ('withdrawal_hold', 'Withdrawal hold'), ('withdrawal_paid', 'Withdrawal paid out'), ('withdrawal_reversal', 'Withdrawal reversed')], max_length=24)),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('equity', 'Equity')], max_length=10)),
                ('purpose', models.CharField(choices=[('player_cash', 'Player cash wallet'), ('pool_hold', 'Draw pool hold'), ('withdrawal_pending', 'Withdrawals in flight'), ('provider_clearing', 'Payment provider clearing'), ('house_revenue', 'House gaming revenue')], max_length=24)),
                ('currency', models.CharField(max_length=3)),
                ('balance', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('amount', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.journaltransaction')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.ledgeraccount')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('wagering_remaining', models.BigIntegerField(default=0)),
                ('total_deposited', models.BigIntegerField(default=0)),
                ('total_withdrawn', models.BigIntegerField(default=0)),
                ('total_staked', models.BigIntegerField(default=0)),
                ('total_won', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='ledger.ledgeraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='journaltransaction',
            index=models.Index(fields=['source_type', 'source_id'], name='ledger_jour_source__808b6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purpose', 'player_cash'), _negated=True), ('balance__gte', 0), _connector='OR'), name='player_cash_non_negative'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['account', '-created_at'], name='ledger_entr_account_17836d_idx'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='entry_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'currency'), name='one_wallet_per_currency'),
        ),
    ]
