# Generated by Django 6.1.1 on 2026-10-02 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_immutable_ledger_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ledgeraccount',
            name='player_cash_non_negative',
        ),
        migrations.AddField(
            model_name='wallet',
            name='bonus_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bonus_wallet', to='ledger.ledgeraccount'),
        ),
        migrations.AlterField(
            model_name='journaltransaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('ticket_purchase', 'Ticket purchase'), ('prize_payout', 'Prize payout'), ('pool_topup', 'House top-up of prize pool'), ('pool_settlement', 'Pool settlement to house'), ('ticket_refund', 'Ticket refund'), ('withdrawal_hold', 'Withdrawal hold'), ('withdrawal_paid', 'Withdrawal paid out'), ('withdrawal_reversal', 'Withdrawal reversed'), ('welcome_bonus', 'Welcome bonus'), ('prize_carryover', 'Prize money carried over')], max_length=24),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='purpose',
            field=models.CharField(choices=[('player_cash', 'Player cash wallet'), ('player_bonus', 'Player bonus (play-only)'), ('pool_hold', 'Draw pool hold'), ('prize_carryover', 'Prize money carried to next batch'), ('withdrawal_pending', 'Withdrawals in flight'), ('provider_clearing', 'Payment provider clearing'), ('house_revenue', 'House gaming revenue')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purpose__in', ['player_cash', 'player_bonus']), _negated=True), ('balance__gte', 0), _connector='OR'), name='player_cash_non_negative'),
        ),
    ]
