# Generated by Django 6.1.1 on 2026-10-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_remove_ledgeraccount_player_cash_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ledgeraccount',
            name='player_cash_non_negative',
        ),
        migrations.AddField(
            model_name='wallet',
            name='coin_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coin_wallet', to='ledger.ledgeraccount'),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='purpose',
            field=models.CharField(choices=[('player_cash', 'Player winnings (withdrawable)'), ('player_coins', 'Player coins (bought, play-only)'), ('player_bonus', 'Player bonus coins (play-only)'), ('pool_hold', 'Draw pool hold'), ('prize_carryover', 'Prize money carried to next batch'), ('withdrawal_pending', 'Withdrawals in flight'), ('provider_clearing', 'Payment provider clearing'), ('house_revenue', 'House gaming revenue')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purpose__in', ['player_cash', 'player_coins', 'player_bonus']), _negated=True), ('balance__gte', 0), _connector='OR'), name='player_cash_non_negative'),
        ),
    ]
